name: Deploy to S3

on:
  push:
    branches:
      - main  # triggers only on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Ensure assets folder exists
        run: |
          if [ ! -d "./assets" ]; then
            echo "Error: assets folder not found!"
            exit 1
          fi

      - name: Sync assets to S3
        run: |
          aws s3 sync ./assets s3://e5tech --delete
